version: 3

files:
  - pattern: .github/workflows/*.yml
  - pattern: .github/workflows/*.yaml

# Do not accept a newly published action release until it has aged for a week.
min_age:
  value: 7
  always: true
